# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('age0_5', models.IntegerField(default=0)),
                ('age6_17', models.IntegerField(default=0)),
                ('age18_64', models.IntegerField(default=0)),
                ('age65', models.IntegerField(default=0)),
                ('agetotal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30)),
                ('alpha_code', models.CharField(max_length=3)),
                ('numeric_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
