# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbproject', '0002_auto_20151219_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('firm_size', models.CharField(max_length=20)),
                ('num_firms', models.IntegerField(default=0)),
                ('num_employees', models.IntegerField(default=0)),
                ('payroll', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('gdp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('unemployment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('uninsured_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('median_hhincome', models.IntegerField(default=0)),
                ('poverty_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('white', models.IntegerField(default=0)),
                ('black', models.IntegerField(default=0)),
                ('asian', models.IntegerField(default=0)),
                ('native_american', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('male', models.FloatField(default=0)),
                ('female', models.FloatField(default=0)),
            ],
        ),
    ]
