# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbproject', '0003_business_economy_employment_healthinsurance_income_race_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('year', models.IntegerField(default=2010)),
                ('homeownership_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='firm_size',
        ),
    ]
